from keyboards.keyboard import markup1
from keyboards.keyboard import markup2
from keyboards.keyboard import markup3
from keyboards.keyboard import markup4
from keyboards.keyboard import markup5
from keyboards.keyboard import markup6
from keyboards.keyboard import markup7
from keyboards.keyboard import markup8
from keyboards.keyboard import markup9
from keyboards.keyboard import markup10
from keyboards.keyboard import markup11
from keyboards.keyboard import markup12
from keyboards.keyboard import markup13
from keyboards.keyboard import markup14
from keyboards.keyboard import markup15
from keyboards.keyboard import markup16
from keyboards.keyboard import markup17
from keyboards.keyboard import markup18
from keyboards.keyboard import markup19
from keyboards.keyboard import markup20
from keyboards.keyboard import markup21
from keyboards.keyboard import markup22